Models/Ingredients.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.ComponentModel.DataAnnotations;


namespace WNWN.Models
{
    public class Ingredients
    {
        [Key]
        public int Id { get; set; }
        public IdentityUser User { get; set; }
        public string Name { get; set; }
        public int GroupsId { get; set; }
        public FoodGroup Groups { get; set; }
        public double Weight { get; set; }
        public int UnitsId { get; set; }
        public Units Units { get; set; }
        public DateTime ExpirationDate { get; set; }
        public DateTime ExpectedDate;

        public override string ToString()
        {
            return Name;
        }

        public override bool Equals(object obj)
        {
            return obj is Ingredients @ingredients &&
                Id == @ingredients.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

Controllers/IngredientsController.cs
using WNWN.ViewModels;
using WNWN.Data;
using WNWN.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace WNWN.Controllers
{
    [Authorize]
    public class IngredientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public IngredientsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Ingredients> ingredients = new List<Ingredients>(_context.Ingredients.Where(x => x.User.UserName == User.Identity.Name).Include(g => g.Groups).Include(u => u.Units).ToList());


            return View(ingredients);
        }
        [HttpGet]
        public IActionResult Add()
        {
            AddIngredientsViewModel addIngredientsViewModel = new AddIngredientsViewModel(_context.Groups.ToList(), _context.Units.ToList());

            return View(addIngredientsViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddIngredientsViewModel addIngredientsViewModel)
        {
            if (ModelState.IsValid)
            {
                var group = _context.Groups.Find(addIngredientsViewModel.FoodGroupId);
                var unit = _context.Units.Find(addIngredientsViewModel.UnitId);

                Ingredients newIngredients = new Ingredients
                {
                    User = _userManager.GetUserAsync(User).Result,
                    Name = addIngredientsViewModel.Name,
                    Groups = group,
                    Weight = addIngredientsViewModel.Weight,
                    ExpirationDate = addIngredientsViewModel.ExpirationDate,
                    Units = unit
                };

                _context.Ingredients.Add(newIngredients);
                _context.SaveChanges();

                return Redirect("/Ingredients");
            }

            return View(addIngredientsViewModel);
        }

        public IActionResult Delete()
        {
            var user = _userManager.GetUserAsync(User).Result;
            var userId = _userManager.GetUserIdAsync(user).Result;
            List<Ingredients> ingredients = new List<Ingredients>(_context.Ingredients.Where(x => x.User.Id == userId).ToList());

            return View(ingredients);
        }

        [HttpPost]
        public IActionResult Delete(int[] ingredientIds)
        {
            foreach (int ingredientId in ingredientIds)
            {
                var ingredient = _context.Ingredients.Find(ingredientId);
                _context.Ingredients.Remove(ingredient);
                _context.SaveChanges();
            }

            return Redirect("/Ingredients");
        }
    }
}

Views/Ingredients/Add.cshtml
@model WNWN.ViewModels.AddIngredientsViewModel


@section Scripts
    {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>
    <!-- MDB -->
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>
@*    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
    <script>
        $(function () {
            $('#datepicker').datetimepicker();
        });

    </script>
    }
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
    <style>
        body {
            background-color: rgb(161,187,195);
        }

        h1 {
            color: black;
        }

        p {
            color: black;
        }
    </style>
    <title>Digital Pantry</title>
</head>
<body>
    <h1>Add Ingredient</h1>

    <form asp-controller="Ingredients" asp-action="Add" method="post">
        <div class="form-group">
            <label asp-for="Name">Ingredient</label>
            <input asp-for="Name" asp-validation-for="Name" />
        </div>
        <div class="form-group">
            <label asp-for="Name">Food Group</label>
            <select asp-for="FoodGroupId" asp-items="Model.Groups"></select>
        </div>
        <div class="form-group">
            <label asp-for="Name">Weight</label>
            <input asp-for="Weight" />
        </div>
        <div class="form-group">
            <label asp-for="Name">Units</label>
            <select asp-for="UnitId" asp-items=Model.Units></select>
        </div>
        <div class="form-group">
            <label asp-for="Name">Expiration Date</label>
            <input asp-for="ExpirationDate" type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" />
        </div>
        <input type="submit" value="Add Ingredient" />
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Views/Ingredients/Delete.cshtml
@model List<WNWN.Models.Ingredients>
@{
}

<h1>Delete Ingredient</h1>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>

    body {
        background-color: rgb(161,187,195);
    }

    h1 {
        color: black;
    }

    p {
        color: black;
    }

    body {
        background-color: rgb(161,187,195);
    }

    h1 {
        color: black;
    }

    p {
        color: black;
    }
</style>


@if (Model.Count == 0)
{
    <p>Your digital pantry is empty.</p>
}
else
{
    <form method="post">
        @foreach (var ing in Model)
        {
            <div class="container">
                <label>
                    <span>@ing.Name</span>
                    <input type="checkbox" name="ingredientIds" value="@ing.Id" class="form-control">
                </label>
            </div>
        }

        <input type="submit" value="Delete Selected Ingredients" class="btn btn-danger">

    </form>
}

Views/Ingredients/Index.cshtml
@model List<WNWN.Models.Ingredients>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: thick solid #ddd;
        }

        th, td {
            text-align: left;
            padding: 16px;
        }

        tr:nth-child(even) {
            background-color: rgb(222,234,237);
        }

        tr:nth-child(odd) {
            background-color: rgb(222,234,237);
        }

        body {
            background-color: rgb(161,187,195);
        }

        h1 {
            color: black;
        }

        p {
            color: black;
        }
        table {
            color: rgb(222,234,237);
        }
    </style>
</head>
<body>

    <h1>Ingredient List</h1>

    <p>
        <a asp-controller="Ingredients" asp-action="Add">Add Ingredient</a>
    </p>


    <p>
        <a asp-controller="Ingredients" asp-action="Delete">Delete Ingredient</a>
    </p>

    @if (Model.Count == 0)
    {
        <p>Your digital pantry is empty.</p>
    }
    else
    {
        <table class="table">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Food Group
                </th>
                <th>
                    Weight
                </th>
                <th>
                    Units
                </th>
                <th>
                    Expiration Date
                </th>
            </tr>
            @foreach (var ing in Model)
            {
                <tr>
                    <td>@ing.Name</td>
                    <td>@ing.Groups.Name</td>
                    <td>@ing.Weight</td>
                    <td>@ing.Units.Name</td>
                    <td>@ing.ExpirationDate</td>
                </tr>
            }
        </table>
    }
</body>
</html>