Controllers/PlannerController.cs
using WNWN.Data;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;


namespace WNWN.Controllers
{
    [Authorize]
    public class PlannerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
  
        public PlannerController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {

            _context.SaveChanges();

            return View();
        }
    }
}

Views/Planner/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model NoIngredients
@*@{
    ViewData["Title"] = "Home Page";
}*@

@if (SignInManager.IsSignedIn(User))
{
    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
        <br>
        <form asp-controller="Planner" asp-action="Index">
            <h3>Please Select Foods You Do Not Wish To Eat.</h3>
            <div>
                @foreach (var option in Model.OptionList)       @*locks up here*@
                {
                    <label><input type="checkbox"> @option</label><br>
                }
            </div>

        @*<div id="options">
            @foreach (var option in Model.OptionList)
            {
                <a asp-controller="Planner" asp-action="Index" asp-route-id="@option.Id">@option.Name</a>
            }
        </div>*@

        </form>
    </body>
    </html>
 }
 else
 {
     <br>
     <br><p>Log in to access your digital pantry. New? Our Register button is up above. All you need is a kitchen scale, your kitchens ingredients, and their expiration dates to keep track of your food to prevent waste.</p>
 }